### ISSUE TITLE
Error trying to upload User Data

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#105]
<img width="1211" alt="screen shot 2016-01-21 at 1 39 17 pm" src="https://cloud.githubusercontent.com/assets/4040084/12495454/a0eb5f50-c044-11e5-8ca4-bd10293c6f44.png">
<img width="864" alt="screen shot 2016-01-21 at 1 39 52 pm" src="https://cloud.githubusercontent.com/assets/4040084/12495457/a4caaa22-c044-11e5-9f5e-f6253f692ad0.png">

The second screenshot shows where the error is occurring. I'm not sure of this is a known issue, this is on the deployed app.

**Comment by phyllers** [comment]
This is the error in the logs for that deployment:

```
Internal Server Error: /projects/data/
Traceback (most recent call last):
  File "/home/vmagent/app/lib/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vmagent/app/lib/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vmagent/app/projects/views.py", line 190, in upload_files
    file_upload.save()
  File "/home/vmagent/app/lib/django/db/models/base.py", line 591, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vmagent/app/lib/django/db/models/base.py", line 619, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/vmagent/app/lib/django/db/models/base.py", line 700, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/vmagent/app/lib/django/db/models/base.py", line 733, in _do_insert
    using=using, raw=raw)
  File "/home/vmagent/app/lib/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vmagent/app/lib/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/vmagent/app/lib/django/db/models/sql/compiler.py", line 919, in execute_sql
    for sql, params in self.as_sql():
  File "/home/vmagent/app/lib/django/db/models/sql/compiler.py", line 877, in as_sql
    for obj in self.query.objs
  File "/home/vmagent/app/lib/django/db/models/fields/files.py", line 301, in pre_save
    file.save(file.name, file, save=False)
  File "/home/vmagent/app/lib/django/db/models/fields/files.py", line 89, in save
    self.name = self.storage.save(name, content)
  File "/home/vmagent/app/lib/django/core/files/storage.py", line 51, in save
    name = self._save(name, content)
  File "/home/vmagent/app/google_helpers/cloud_file_storage.py", line 34, in _save
    media_body=media
  File "/home/vmagent/python_vm_runtime/lib/oauth2client/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/app/lib/googleapiclient/http.py", line 722, in execute
    body=self.body, headers=self.headers)
  File "/home/vmagent/python_vm_runtime/lib/oauth2client/oauth2client/client.py", line 562, in new_request
    redirections, connection_type)
  File "/home/vmagent/python_vm_runtime/lib/httplib2/httplib2/__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/vmagent/python_vm_runtime/lib/httplib2/httplib2/__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/vmagent/python_vm_runtime/lib/httplib2/httplib2/__init__.py", line 1302, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```

**Comment by LoveAndCoding** [comment]
Ughhh. I hate `BadStatusLine`. It's a terrible error. Basically, that means GAE threw a non-descript error while trying to upload the data to the cloud. Usually a connection error between the GAE instance and the cloud api. It's very intermittent. Unless it's not. There are times when the machine might get "stuck" in a state where it can never get a good upload. Which seems to be only fixed by resetting the machines.

I investigated this and couldn't find any good info about a reliable way to fix the random ones that crop up. Most people just seem to recommend retrying a few times when you get this status code. Which is not the best strategy. But probably better than what is in place.

**Comment by phyllers** [comment]
Did not get any error today. I'm going to close this.
