### ISSUE TITLE
Cannot start new workbook from variable favourites list

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#135]
<img width="1109" alt="screen shot 2016-02-08 at 12 12 26 pm" src="https://cloud.githubusercontent.com/assets/4040084/12897619/46f2d6dc-ce5d-11e5-9b92-6ca73b01657c.png">

Got this from the dropdown in variable favourites list.

**Comment by rgbohner** [comment]
Additional bug info : metadata:
{…}
textPayload:
"Internal Server Error: /workbooks/create_with_variables
Traceback (most recent call last):
  File "/home/vmagent/app/lib/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/vmagent/app/lib/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/home/vmagent/app/workbooks/views.py", line 96, in workbook_create_with_variables
    var_list_model = VariableFavorite.objects.get(id=var_list_id)
  File "/home/vmagent/app/lib/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(_args, *_kwargs)
  File "/home/vmagent/app/lib/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: VariableFavorite matching query does not exist.
"
insertId:
"2016-02-09|09:49:56.809465-08|10.106.152.213|1594254911"
log:
"appengine.googleapis.com/app"
}
