### ISSUE TITLE
google apps does not recognize basespace url on staging

### ISSUE THREAD

**Issue by rgbohner** [BlinkUX/ISB-CGC#152]
Traceback (most recent call last):
  File "/home/vmagent/app/lib/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/vmagent/app/projects/views.py", line 685, in upload_basespace_files
    basespace_response = write_response_to_basespace(result, access_token, session_uri)
  File "/home/vmagent/app/projects/views.py", **line 702, in write_response_to_basespace**
    h.request('POST', session_uri, status_params_enc, headers)
  File "/usr/lib/python2.7/httplib.py", line 962, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 996, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 958, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 818, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 780, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1161, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
"

**Comment by rgbohner** [comment]
exception was added in commit 4edaaaaf1e33ca2746dff065fd9e03f37b238b17 to handle this error.  The basespace app might list the analysis 'import' as running but the import will still complete to the data processor

**Comment by rgbohner** [comment]
This issue was addressed when moved to the production environment
