### ISSUE TITLE
Error while uploading "other"-type user data with patient barcodes

### ISSUE THREAD

**Issue by kleisb** [BlinkUX/ISB-CGC#159]
User data processor configuration file is attached. Please let me know if a sample of the data file is needed as well.
@
[config.zip](https://github.com/BlinkUX/ISB-LSDF/files/145349/config.zip)

Command line and output:

```
vagrant@ubuntu-14:~/parentDir/User-Data-Processor$ python ./user-data-processor.py configs/LGG-Annotation.1-24-2014_cluster.not_shared.config.json 
Number of user_gen files:  1
Number of molecular files:  0
Number of low level files:  0
Begin processing user_gen files.
Traceback (most recent call last):
  File "./user-data-processor.py", line 138, in <module>
    './config/data_etl_template.json',
  File "./user-data-processor.py", line 76, in main
    user_gen_list)
  File "/home/vagrant/parentDir/User-Data-Processor/user_gen/user_gen_processing.py", line 71, in process_user_gen_files
    insert_metadata(data_df, metadata, cloudsql_tables['METADATA_DATA'])
  File "/home/vagrant/parentDir/User-Data-Processor/user_gen/user_gen_processing.py", line 137, in insert_metadata
    sample_barcodes = list(set([k for d, k in data_df['sample_barcode'].iteritems()]))
  File "/home/vagrant/www/lib/pandas/core/frame.py", line 1914, in __getitem__
    return self._getitem_column(key)
  File "/home/vagrant/www/lib/pandas/core/frame.py", line 1921, in _getitem_column
    return self._get_item_cache(key)
  File "/home/vagrant/www/lib/pandas/core/generic.py", line 1090, in _get_item_cache
    values = self._data.get(item)
  File "/home/vagrant/www/lib/pandas/core/internals.py", line 3102, in get
    loc = self.items.get_loc(item)
  File "/home/vagrant/www/lib/pandas/core/index.py", line 1692, in get_loc
    return self._engine.get_loc(_values_from_object(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:3979)
  File "pandas/index.pyx", line 157, in pandas.index.IndexEngine.get_loc (pandas/index.c:3843)
  File "pandas/hashtable.pyx", line 668, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12265)
  File "pandas/hashtable.pyx", line 676, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12216)
KeyError: 'sample_barcode'
```

**Comment by phyllers** [comment]
Can you provide the file you uploaded?

**Comment by kleisb** [comment]
The file `LGG-Annotation.1-24-2014_cluster.forXmlMerge.tsv` should be in the "Shared with Blink" Google Drive folder.

**Comment by rgbohner** [comment]
I assigned this to you @phyllers let me know if this is incorrect

**Comment by phyllers** [comment]
@kleisb I'm able to upload that file if you select Sample Barcode for the Patient barcode field. We require that all files have a sample barcode.

@rgbohner I think that's still true, correct?

**Comment by kleisb** [comment]
@phyllers I originally selected "patient barcodes" for the schema configuration in the upload view for this file, as my understanding is that using patient barcodes should also be possible. The file was part of the test set given to me by Sheila, so I assumed that files with patient barcodes _only_ should also work.

**Comment by phyllers** [comment]
I'm closing this as it's working as designed.
