### ISSUE TITLE
Error while uploading data (/projects/data/)

### ISSUE THREAD

**Issue by kleisb** [BlinkUX/ISB-CGC#164]
The file is attached. I tested trying the upload the data both as a standalone study and a study extending TCGA.
[data.zip](https://github.com/BlinkUX/ISB-LSDF/files/145790/data.zip)

The POST to `/projects/data/` on line 319 (stack trace in Django debug view). Same from application log:

```
ERROR    2016-02-25 01:17:15,611 base.py:231] Internal Server Error: /projects/data/
Traceback (most recent call last):
  File "/home/vagrant/www/lib/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/www/lib/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/www/projects/views.py", line 146, in upload_files
    if request.POST['project-type'] == 'new':
  File "/home/vagrant/www/lib/django/utils/datastructures.py", line 319, in __getitem__
    raise MultiValueDictKeyError(repr(key))
```

Also seeing this error:

```
ERROR    2016-02-25 01:24:10,735 base.py:231] Internal Server Error: /projects/data/
Traceback (most recent call last):
  File "/home/vagrant/www/lib/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/www/lib/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/www/projects/views.py", line 190, in upload_files
    file_upload.save()
  File "/home/vagrant/www/lib/django/db/models/base.py", line 591, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vagrant/www/lib/django/db/models/base.py", line 619, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/vagrant/www/lib/django/db/models/base.py", line 700, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/vagrant/www/lib/django/db/models/base.py", line 733, in _do_insert
    using=using, raw=raw)
  File "/home/vagrant/www/lib/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/www/lib/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/vagrant/www/lib/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/www/lib/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/www/lib/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/www/lib/django/db/backends/mysql/base.py", line 128, in execute
    return self.cursor.execute(query, args)
  File "/home/vagrant/www/lib/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/home/vagrant/www/lib/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
Warning: Data truncated for column 'file' at row 1
```

**Comment by kleisb** [comment]
The JSON object from the POST request (not the same request that produced the errors - I used the upload view for the same file again, with same column config):

```
{"name":"Bindea_immune_scores_20151104.truncated.10lines.tsv","size":7048,"columns":[{"name":"bcr_patient_barcode","type":"string","colMatch":false,"index":0,"ignored":false,"controlled":{"displayName":"Sample Barcode","type":"string","key":"sample_barcode"}},{"name":"N:SAMP:Bindea_immune_aDC","type":"float","colMatch":false,"index":1,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_Angiogenesis","type":"float","colMatch":false,"index":2,"ignored":false},{"name":"N:SAMP:Bindea_immune_APM1","type":"float","colMatch":false,"index":3,"ignored":false},{"name":"N:SAMP:Bindea_immune_APM2","type":"float","colMatch":false,"index":4,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_B_cells","type":"float","colMatch":false,"index":5,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_CD8_T_cells","type":"float","colMatch":false,"index":6,"ignored":false},{"name":"N:SAMP:Bindea_immune_CTLA4","type":"float","colMatch":false,"index":7,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_Cytotoxic_cells","type":"float","colMatch":false,"index":8,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_DC","type":"float","colMatch":false,"index":9,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_Eosinophils","type":"float","colMatch":false,"index":10,"ignored":false},{"name":"N:SAMP:Bindea_immune_iDC","type":"float","colMatch":false,"index":11,"ignored":false},{"name":"N:SAMP:Bindea_immune_Lymph_vessels","type":"float","colMatch":false,"index":12,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_Macrophages","type":"float","colMatch":false,"index":13,"ignored":false},{"name":"N:SAMP:Bindea_immune_Mast_cells","type":"float","colMatch":false,"index":14,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_Neutrophils","type":"float","colMatch":false,"index":15,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_NK_CD56bright_cells","type":"float","colMatch":false,"index":16,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_NK_CD56dim_cells","type":"float","colMatch":false,"index":17,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_NK_cells","type":"float","colMatch":false,"index":18,"ignored":false},{"name":"N:SAMP:Bindea_immune_PD1","type":"float","colMatch":false,"index":19,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_pDC","type":"float","colMatch":false,"index":20,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_PDL1","type":"float","colMatch":false,"index":21,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_T_cells","type":"float","colMatch":false,"index":22,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_T_helper_cells","type":"float","colMatch":false,"index":23,"ignored":false},{"name":"N:SAMP:Bindea_immune_Tcm_cells","type":"float","colMatch":false,"index":24,"ignored":false},{"name":"N:SAMP:Bindea_immune_Tem_cells","type":"float","colMatch":false,"index":25,"ignored":false},{"name":"N:SAMP:Bindea_immune_Tfh_cells","type":"float","colMatch":false,"index":26,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_Tgd_cells","type":"float","colMatch":false,"index":27,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_Th1_cells","type":"float","colMatch":false,"index":28,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_Th17_cells","type":"float","colMatch":false,"index":29,"ignored":false,"controlled":null},{"name":"N:SAMP:Bindea_immune_Th2_cells","type":"float","colMatch":false,"index":30,"ignored":false},{"name":"N:SAMP:Bindea_immune_Treg_cells","type":"float","colMatch":false,"index":31,"ignored":false,"controlled":null}],"platform":"platform_5","pipeline":"platform_5"}
```

**Comment by kleisb** [comment]
Error occurs also with the file `GTEx_subset_SampleAttributes.txt`, that successfully uploaded today before pulling latest changes.

**Comment by kleisb** [comment]
Upload of `GTEx_subset_SampleAttributes.txt` fails only if _adding a study to an existing project_.

**Comment by phyllers** [comment]
When I tried this, I was able create a new study, but not _extend_ an existing study's data. Is that what you meant?

**Comment by kleisb** [comment]
Tried to upload the data attached to the issue, by creating an entirely new project. Error:

```
ERROR    2016-02-25 02:22:12,036 base.py:231] Internal Server Error: /projects/data/
Traceback (most recent call last):
  File "/home/vagrant/www/lib/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/www/lib/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/www/projects/views.py", line 190, in upload_files
    file_upload.save()
  File "/home/vagrant/www/lib/django/db/models/base.py", line 591, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vagrant/www/lib/django/db/models/base.py", line 619, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/vagrant/www/lib/django/db/models/base.py", line 700, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/vagrant/www/lib/django/db/models/base.py", line 733, in _do_insert
    using=using, raw=raw)
  File "/home/vagrant/www/lib/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/www/lib/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/vagrant/www/lib/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/www/lib/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/www/lib/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/www/lib/django/db/backends/mysql/base.py", line 128, in execute
    return self.cursor.execute(query, args)
  File "/home/vagrant/www/lib/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/home/vagrant/www/lib/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
Warning: Data truncated for column 'file' at row 1
```

**Comment by kleisb** [comment]
@phyllers I selected `A NEW STUDY FOR AN EXISTING PROJECT` in the Data Upload view and picked an existing project, then filled in the study name for a new study.

**Comment by phyllers** [comment]
Ahh okie dokie. I am mistaken. Thanks!

**Comment by kleisb** [comment]
I don't remember whether or not I was adding a study to an existing project or not when I filed this issue. It could be that the first included stackdump is from adding a study to an existing project, and the second from a possibly broken file.

**Comment by phyllers** [comment]
I found a bug and a fix that should address extending project data. 

https://github.com/isb-cgc/ISB-CGC-Webapp/blob/master/static/js/data_upload.js#L603

**Comment by phyllers** [comment]
Pushed change

https://github.com/isb-cgc/ISB-CGC-Webapp/commit/11b8c44b1e375e77656055d83cc0971174dcd6c3

**Comment by phyllers** [comment]
@kleisb Please test this on mvm. I was able to upload data just fine.

**Comment by kleisb** [comment]
I created a project called `Data with TCGA sample barcodes` in MVM. The attached file was sent to the data processor succesfully.

Note that I have not determined why the file I originally attached does not pass the pre-upload checks. The error message mentions possible newlines in the file. That file was created by just running `head -n 11` in shell on the original file.

[Bindea_immune_scores_20151104.16_char_barcodes.tsv.zip](https://github.com/BlinkUX/ISB-LSDF/files/147519/Bindea_immune_scores_20151104.16_char_barcodes.tsv.zip)
