### ISSUE TITLE
save as plot does not work

### ISSUE THREAD

**Issue by rgbohner** [BlinkUX/ISB-CGC#174]
ERROR    2016-02-26 02:33:15,969 base.py:231] Internal Server Error: /cohorts/save_cohort_from_plot/
Traceback (most recent call last):
  File "/home/vagrant/www/lib/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/vagrant/www/lib/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/home/vagrant/www/lib/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/home/vagrant/www/cohorts/views.py", line 840, in save_cohort_from_plot
    source_list.append(Source(parent=source_plot.cohort.cohort, cohort=cohort, type=Source.PLOT_SEL))
AttributeError: 'Worksheet_plot' object has no attribute 'cohort'

**Comment by rgbohner** [comment]
This is most likely a regression from the multi cohort add on plots

**Comment by phyllers** [comment]
working
