### ISSUE TITLE
User Upload : Error while applying/creating a new cohort from user project that contains extended studies

### ISSUE THREAD

**Issue by kleisb** [BlinkUX/ISB-CGC#186]
Data used when this error occurred is attached.
[bindea.16_char_barcodes.split.zip](https://github.com/BlinkUX/ISB-LSDF/files/148819/bindea.16_char_barcodes.split.zip)

To replicate:
- Create a new project and study
- Use first file (part 1 of 3) as the study data
- Create new study in the same project, such that the study extends the previously uploaded study
- Use the second file (part 2 of 3) as the study data
- Try to create a new cohort of the whole project (not either one of the studies)

Application log:

```
ERROR    2016-02-26 19:58:33,604 base.py:231] Internal Server Error: /cohorts/save_cohort_for_workbook/
Traceback (most recent call last):
  File "/home/vagrant/www/lib/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/www/lib/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/www/cohorts/views.py", line 402, in save_cohort_for_existing_workbook
    return save_cohort(request=request, workbook_id=request.POST.get('workbook_id'), worksheet_id=request.POST.get("worksheet_id"))
  File "/home/vagrant/www/lib/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vagrant/www/lib/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/vagrant/www/cohorts/views.py", line 512, in save_cohort
    items = items['items']
KeyError: 'items'
```

**Comment by phyllers** [comment]
@rgbohner For testing:

BlinkUX / ISB / CGC Shared > GTEx data example > GTEx_subset_GExpMatrix.tsv --> Molecular Gene Expression data

BlinkUX / ISB / CGC Shared > GTEx data example > GTEx_subset_SampleAttributes.txt --> Other data

BlinkUX / ISB / CGC Shared > TCGA annotations examples > LGG-Annotation.1-24-2014_cluster.forXmlMerge.tsv --> Extending TCGA data

Let me know if this helps or not, but I think this is what you were looking for.
