### ISSUE TITLE
Unable to save cohort using user data

### ISSUE THREAD

**Issue by rgbohner** [BlinkUX/ISB-CGC#193]
Internal Server Error: /cohorts/save_cohort/
Traceback (most recent call last):
  File "/home/vmagent/app/lib/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/vmagent/app/lib/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/home/vmagent/app/lib/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "/home/vmagent/app/cohorts/views.py", line 512, in save_cohort
    items = items['items']
KeyError: 'items'

**Comment by rgbohner** [comment]
THis is potentially related to issue #186

**Comment by rgbohner** [comment]
This error is an effect on the fundamental problem of filters on data not having data returned.  An data check was added to validate the data returned on filters before cohorts are created

**Comment by rgbohner** [comment]
#186 should resolve this issue
