### ISSUE TITLE
Server Error on viewing existing workbook

### ISSUE THREAD

**Issue by litopia** [BlinkUX/ISB-CGC#94]
Cannot view existing workbook.

**Comment by LoveAndCoding** [comment]
Stacktrace:

```
Traceback (most recent call last):
  File "/home/vmagent/app/lib/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vmagent/app/lib/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/vmagent/app/workbooks/views.py", line 150, in workbook
    if variable.project: #project will be null if the variable is from TCGA
AttributeError: 'Worksheet_variable' object has no attribute 'project'
```
